package com.epam.esm.validator;

public enum ValidationError {
    TAG_NAME_IS_EMPTY_OR_NULL,
    TAG_NAME_LENGTH_IS_SHORT,
    TAG_NAME_LENGTH_IS_LONG,
    TAG_NAME_HAVE_NOT_CORRECT_SYMBOLS,

    GIFT_CERTIFICATE_NAME_IS_EMPTY_OR_NULL,
    GIFT_CERTIFICATE_NAME_LENGTH_IS_SHORT,
    GIFT_CERTIFICATE_NAME_LENGTH_IS_LONG,
    GIFT_CERTIFICATE_NAME_HAVE_NOT_CORRECT_SYMBOLS,

    GIFT_CERTIFICATE_DESCRIPTION_IS_EMPTY_OR_NULL,
    GIFT_CERTIFICATE_DESCRIPTION_LENGTH_IS_SHORT,
    GIFT_CERTIFICATE_DESCRIPTION_LENGTH_IS_LONG,
    GIFT_CERTIFICATE_DESCRIPTION_HAVE_NOT_CORRECT_SYMBOLS,

    GIFT_CERTIFICATE_DURATION_LESS_THAN_ALLOWED_VALUE,
    GIFT_CERTIFICATE_DURATION_MORE_THAN_ALLOWED_VALUE,

    GIFT_CERTIFICATE_PRICE_IS_LESS_THAN_ALLOWED_VALUE,
    GIFT_CERTIFICATE_PRICE_IS_MORE_THAN_ALLOWED_VALUE;
}
